show field type when editing a field
ushahidi/platform-client pull request #1559
Opened 2020-10-11 19:07 UTC by ypresion

This pull request makes the following changes:
- 'Edit field' in surveys now shows the type of the field 
![d9f145bc5bc2a1a1d55b8e8ecc32aee6](https://user-images.githubusercontent.com/45670033/95666174-1b1adf80-0b4f-11eb-8f7d-42a3dc618923.png)

Testing checklist:
- [ ] log into your deployment
- [ ] go to survey
- [ ] select a field to edit
- [ ] modal's title should be in format '**Edit** *field type* **field**'

- [x] I certify that I ran my checklist

[Fixes # 1555 in ushahidi/platform](https://github.com/ushahidi/platform/issues/1555)

Ping @ushahidi/platform

2020-10-11 19:11 UTC, ypresion commented
[clabot:check]

2020-10-15 09:33 UTC, Angamanga requested changes
Well done! I just left a small change in the comments, otherwise it works fine!

2020-10-15 09:33 UTC, Angamanga commented on app/settings/surveys/survey-editor.directive.js
> +        var title = attribute.id ? $translate.instant('survey.edit_field', {fieldType: fieldType}) : 'survey.add_field';
Could you add the type of field when adding a new field as well? Same method as when editing, just add the translate-values to "survey.add_field" as well.

2020-10-15 09:33 UTC, Angamanga commented on app/settings/surveys/survey-editor.directive.js
> +    function getFieldType(attribute) {
Neat solution!

2020-11-20 10:00 UTC, Angamanga commented
@ypresion Do you plan to fix the requested changes for this pr? Otherwise I'll merge it into its own branch so someone else can continue 👍

2020-11-27 15:40 UTC, Angamanga commented
Closing this in favour of https://github.com/ushahidi/platform-client/pull/1630

2020-11-27 15:40 UTC, closed without merging