improved accessibility in form labelling #4079
ushahidi/platform-client pull request #1561
Opened 2020-10-11 22:54 UTC by amycruz97

This pull request makes the following changes:
-

Testing checklist:
- [ ]

- [x] I certify that I ran my checklist

Fixes ushahidi/platform #4079.

Ping @ushahidi/platform

2020-10-12 22:51 UTC, amycruz97 commented
how can i sign the contributor agreements

2020-10-13 19:57 UTC, rowasc commented
@amycruz97 try https://docs.google.com/forms/d/15LyeKTOP36T5u3290o4hsmqv79v-m_s2QSmgMJXpYp8/viewform here 
Then run "[clabot:check]" (without the quotation marks) so the bot knows.

2020-10-13 23:12 UTC, amycruz97 commented
> @amycruz97 try https://docs.google.com/forms/d/15LyeKTOP36T5u3290o4hsmqv79v-m_s2QSmgMJXpYp8/viewform here
> Then run "[clabot:check]" (without the quotation marks) so the bot knows.

run [clabot:check] where ..in my local terminal or where

2020-10-13 23:17 UTC, amycruz97 commented
[clabot:check]

2020-10-14 15:46 UTC, amycruz97 commented
clabot:check

2020-10-14 22:00 UTC, amycruz97 commented
[clabot:check]

2020-10-15 09:40 UTC, Angamanga commented
@amycruz97 Could you add a test-checklist for this please?

2020-10-15 10:09 UTC, amycruz97 commented
teat checklist how do i do that

2020-10-16 07:57 UTC, Angamanga commented
@amycruz97 A test-checklist is a list you add to the description of the PR and that works as a guide when doing review and QA. You can see an example here: https://github.com/ushahidi/platform-client/pull/1564

2020-10-19 00:04 UTC, amycruz97 commented
[clabot:check]

2020-10-19 00:04 UTC, amycruz97 commented
[clabot:check]

2020-10-19 00:06 UTC, amycruz97 commented
[clabot:check]

2020-10-19 00:07 UTC, amycruz97 commented
> @amycruz97 A test-checklist is a list you add to the description of the PR and that works as a guide when doing review and QA. You can see an example here: #1564

yh i added a test checklist thanks

2020-10-20 10:33 UTC, amycruz97 commented
@rowasc pls check this pull request

2020-10-20 21:42 UTC, rowasc requested changes
Hey @amycruz97 this is a good start ! Thanks
A couple of things
- a lot of labels are simply missing the text description on them (as shown here https://github.com/ushahidi/platform/issues/4079) 
- please use hyphen instead of underscore in the IDs 
Thank you !

2020-10-20 21:42 UTC, rowasc commented on app/common/directives/file-upload.html
> +<label>
The label text is missing here

2020-10-20 21:42 UTC, rowasc commented on app/common/directives/filter-system/filter-searchbar.html
> +            <label>
The label text is missing here

2020-10-20 21:42 UTC, rowasc commented on app/main/activity/activity-timeline.html
> +               <label>
The label text is missing here

2020-10-21 01:48 UTC, amycruz97 commented
> Hey @amycruz97 this is a good start ! Thanks
> A couple of things
> 
> * a lot of labels are simply missing the text description on them (as shown here [ushahidi/platform#4079](https://github.com/ushahidi/platform/issues/4079))
> * please use hyphen instead of underscore in the IDs
>   Please note I only added specific comments in a few instances but the label text are missing in others as well.
>   Thank you !

Thanks on it

2020-10-22 03:24 UTC, amycruz97 commented
@rowasc pls i have made the changes, kindly review the pull request Thanks

2020-10-26 11:25 UTC, amycruz97 commented
@Angamanga @rowasc pls review the pull request

2020-11-23 10:58 UTC, Angamanga commented
Hi @amycruz97! This looks fine now, thank you for your contribution. As you see there are a lot of conflicts in the files, it means that these issues was already fixed by other PRs and I will close this. It doesn't mean we don't value your work and it is still counted for in the Outreachy evaluation, its just that we had so many contributors this year working on the same issues. Thank you again for your hard work 🎉 .

2020-11-23 10:58 UTC, closed without merging