Add button role to improve accessibility in common/directives #4111
ushahidi/platform-client pull request #1578
Opened 2020-10-16 04:02 UTC by onyeepeace

This pull request makes the following changes:
- Adds button role to improve accessibility

Testing checklist:
- [ ] The buttons which are not button elements now act as buttons

- [ ] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

2020-10-20 07:23 UTC, renujain31 requested changes
Hey @onyeepeace! It looks good to me just one change.

2020-10-20 07:23 UTC, renujain31 commented on app/common/directives/first-time-config.html
> +</modal>
Hey! Can you remove this change. Just add a newline after `</modal>` and it should be fine.

2020-10-20 18:46 UTC, renujain31 approved these changes
Hey, now its perfectly good 🎉 

Thanks @onyeepeace for your contribution.

2020-10-20 19:54 UTC, onyeepeace commented
Thank you

2020-10-20 22:16 UTC, rowasc approved these changes
Brilliant, thank you ! @Obadha2 please test when you get a chance!

2020-10-28 09:44 UTC, merged

2020-10-30 10:04 UTC, Obadha2 commented
QA'd. passes. 👍