Adding role button on a tags #4133
ushahidi/platform-client pull request #1582
Opened 2020-10-16 14:06 UTC by muchirijane

This pull request makes the following changes:
- Adding role button and tabindex = 0  to a tags which act as buttons. 

Testing checklist:
- [ ]

- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

2020-10-20 06:25 UTC, renujain31 approved these changes
Hey! They are great! 
🎉 on already adding tabindex with this. Thanks @muchirijane for your contribution.

@Angamanga @rowasc Can you also review this once.

2020-10-20 06:32 UTC, muchirijane commented
@renujain31 Thank you, learning a lot in the process.

2020-10-20 07:03 UTC, renujain31 commented
Hey, just noticed you forgot to add the testing checklist.

2020-10-20 09:20 UTC, muchirijane commented
Let me add it.

2020-10-22 05:04 UTC, muchirijane commented
Hey, @rowasc thank you. 
I have added made the changes. Please let me know if I should change anything else.

2020-10-23 22:04 UTC, rowasc commented
@muchirijane please update the checklist to include what changed. This is okay as a starting point but someone reading it would have no idea of what buttons to look at for instance :/ 
Thank you ! the changes themselves look good

2020-10-24 07:51 UTC, muchirijane commented
Hey @rowasc, I have added the specific buttons I changed in the checklist. 
For more changes let me know.

2020-10-28 17:59 UTC, Angamanga requested changes
Thank you for your contribution! Please go through the changes and test if you can 1. tab to them from the keyboard and 2. Make sure the same action as when you click that element happens when you press enter.

2020-10-28 17:59 UTC, Angamanga commented on app/main/posts/collections/mode-context.html
> +            <a role="button" tabindex="0" ng-click="clearFilters()" type="button" class="button-link">
Even though we have the class "button" here (which is a mistake we made when choosing the class-name), this element looks like a link and behaves like one so we should not add the role="button" here. Also, could you please test this works when tabbing to the link and clicking space or enter?

2020-10-28 17:59 UTC, Angamanga commented on app/main/posts/savedsearches/mode-context.html
>                  <svg class="iconic">
Same here as for "collections" above.

2020-10-28 17:59 UTC, Angamanga commented on app/main/posts/views/filters/filter-posts.html
>              <sort-and-filter-counter></sort-and-filter-counter>
We use the class button here, but does this element need focus? It is actually the parent-div that needs focus and toggles the dropdown so you can remove the tabindex from here.

2020-11-23 11:00 UTC, Angamanga commented
@muchirijane Do you plan to fix the requested changes for this pr? Otherwise I'll merge it into its own branch so someone else can continue 👍

2020-11-23 11:26 UTC, muchirijane commented
@Angamanga Hey, you can go ahead and put it on its branch. Thanks 👍🏽

2020-12-10 08:58 UTC, closed without merging