4044 - Remove default value for fields that don't use it in post created
ushahidi/platform-client pull request #1584
Opened 2020-10-16 18:37 UTC by Ifycode

**This pull request makes the following changes:**
- Fixes ushahidi/platform#4044

**Observations:**
Fields that have the default value input found in settings > surveys > create a new survey > add field grouped below with observations stated.

**Default values that show on created post:**
- Short Text
- Long Text
- Select
- Radio Buttons
- Check Boxes
- Mark Down

**Default values that **only** work when the right values are entered (Ask mentors before removing):**
- Number (decimal) e.g. 1
- Number (Integer) e.g 1
- Date e.g 16 October, 2020
- Date & Time e.g 16 October, 2020 7:14 pm
- Embed video e.g https://www.youtube.com/watch?v=vpQDkEgO-kA

Haven't been able to assess this yet (Ask mentors):
- Related post

**Default values that don't work at all in post created:**
- Location

**Steps taken:**
- Changes made in attribute-editor.html and attribute-editor.directive.js. 
- Added new function  ($scope.canDisplayDefaultValue) and included location among the inputs to be omitted/removed in attribute-editor.directive.js. 
- Applied it on the elements to be hidden (location & label) with ng-If directive.

**Testing checklist:**
- [x] Check for default values that don't work at all in post created
- [x] Remove default values that don't work at all in post created

- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

2020-10-21 09:47 UTC, Angamanga requested changes
I think you have based this branch out of your branch for this pr: https://github.com/ushahidi/platform-client/pull/1564. Could you try to rebase this to the develop-branch instead? We want to keep the different changes separate. There is a good guide here: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

2020-10-21 16:59 UTC, Ifycode commented
Oh... I was wondering why I had 3 commits instead of just this one commit only. I will follow the link/guide you sent me to rebase it. But i'm still a bit confused about what happened. I tried to browse about it but i don't i have seen anything related to what must have caused this on my end. Maybe you can also help with any link useful to understanding how I made this mistake?

2020-10-22 00:45 UTC, Ifycode commented
Hi @Angamanga After I did the git push -f command, it refused to go through and asked me to use this command: git push --set-upstream origin 4044-defaultValue, which I did. I'm seeing "Merge branch '4044-defaultValue' of github.com:Ifycode/platform-client into 4044-defaultValue"

2020-10-24 21:04 UTC, Ifycode commented
I created a new branch, made the fixes there and sent a fresh PR. [Please review the new PR I have made instead](https://github.com/ushahidi/platform-client/pull/1600) @Angamanga Thanks.

2020-10-28 18:03 UTC, Angamanga commented
Thanks @Ifycode! I'm closing this in favour of https://github.com/ushahidi/platform-client/pull/1600 👍

2020-10-28 18:03 UTC, closed without merging