Added labels for the search and date inputs #4123
ushahidi/platform-client pull request #1587
Opened 2020-10-18 18:34 UTC by muchirijane

This pull request makes the following changes:
- Added labels for accessibility for the search and date inputs. 

Testing checklist:
- [ ]

- [x] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

2020-10-20 06:40 UTC, muchirijane commented
Hey @rowasc and @Angamanga, I created this issue https://github.com/ushahidi/platform/issues/4123 to add labels to the search and date inputs. Hope these changes are okay.

2020-10-20 15:39 UTC, rowasc requested changes
Hey @muchirijane thanks for your contribution. 
A couple of questions
1. Why are we adding an empty label here? I don't see any label text added so I don't know how it would help :/ confused but maybe it's just me. 
2. Can you also link to the issue and add a testing checklist?

2020-10-20 16:44 UTC, muchirijane commented
@rowasc, I thought all inputs should have the label tag. Saw an example in one of the files from the data-export

`<label for="private" translate="data_export.private_desc"></label> 
<input id="private" type="radio" ng-value="true" ng-model="details.private">`

But if I go it wrong I can close the Pull Request. 💯

2020-10-20 21:56 UTC, rowasc commented
@muchirijane you are correct that all inputs should have a label, but the label should make sense/be useful. Otherwise, when someone using a screen reader tries to use it, they just get that blank label (so it doesn't actually help). Does that make sense?
Please don't close the pull request if you plan to continue working on this issue, as mentioned in another PR, when you get feedback you just send updates to the same pull request, no need to close and reopen. That helps both you (because you keep track of the feedback more easily) and the reviewers, because we have more context at the time of review and avoid crashing between each other's feedback.
Of course, if you don't plan to finish this issue, then let me know and I'll close this and assign the ticket to someone else. No stress.
Thanks!

2020-10-22 12:19 UTC, muchirijane commented
Hey @rowasc, I have made the changes 💯 .
 Hope the changes are now better associated with the issue.

2020-10-23 22:02 UTC, rowasc requested changes
hey, thank you. Just a couple of small edits needed, noted in the code. Please also include, in the test checklist, a request to test the behavior of the inputs (ie: "the start date is set correctly") just to make sure it's clear where to look and what to look for in terms of regression testing. Thanks!

2020-10-23 22:02 UTC, rowasc commented on app/main/posts/views/filters/filter-location.html
> +            <label for ="enter-location">Enter city or address</label>
the space betwen for and = should be removed

2020-10-24 07:04 UTC, muchirijane commented
Hey, @rowasc I have made the changes in the code and added the changes in the checklist. 
Let me know if there are any changes I should make.

2020-10-28 17:31 UTC, rowasc requested changes
Hi. Thanks for your contribution. Some of the requested changes marked in the PR are still pending. Thanks!

2020-10-28 20:17 UTC, muchirijane commented
Hey @rowasc, Updated the ID of the last part. Thanks

2020-11-23 13:53 UTC, Angamanga commented
Closing this, most of the changes was fixed in https://github.com/ushahidi/platform/issues/4081, hence the merge-conflicts.

2020-11-23 13:53 UTC, closed without merging