New survey-button is not rtl #3641
ushahidi/platform-client pull request #1597
Opened 2020-10-21 20:12 UTC by hariclerry

This pull request makes the following changes:
-Re-position the survey by moving the yellow button to the left and text to the right

Testing checklist:
- [ ] Yellow new survey button was on the right and text was on the left
- [ ] Yellow new survey button is now on the left and text is on the right
- [ ] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

2020-10-21 20:16 UTC, hariclerry commented
[clabot:check]

2020-10-21 20:19 UTC, hariclerry commented
[clabot:check]

2020-10-21 20:21 UTC, hariclerry commented
Hello @Angamanga and @rowasc, this pull request is ready for review. Thanks

2020-10-22 15:02 UTC, rowasc commented
@hariclerry hey can you sign the CLA ? https://docs.google.com/forms/d/15LyeKTOP36T5u3290o4hsmqv79v-m_s2QSmgMJXpYp8/viewform Thanks!

2020-10-22 15:04 UTC, rowasc commented
also @hariclerry would you mind adding two screenshots to the pull request description, one with the UI using RTL (ie with Arabic language) and one with english/spanish/any LTR languages?

Thanks!

2020-10-22 18:31 UTC, hariclerry commented
[clabot:check]

2020-10-22 18:32 UTC, hariclerry commented
Sure @rowasc!

2020-10-23 12:23 UTC, hariclerry commented
Hello @rowasc. The pull request has been updated accordingly. Thank you for the clarity between RTL and LTR languages, it helped in clarifying the scope of the issue/task. I'm waiting for more reviews and feedback. Thanks

2020-10-23 21:25 UTC, rowasc requested changes
Thanks @hariclerry!  The screenshots look great now ! Nice job. 
As a change request: 
- the css change should be in the pattern library (the HTML change is fine here). https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives/setting-up-the-pattern-library-for-development linking dev docs in case you don't have it yet. 
- as a general rule, avoid using !important and focus instead of using the most specific selector that will work and be usable. This is because relying too much on !important ends up with a mess that's hard to maintain

@Angamanga tagging in case you can help guide them if they need it

2020-10-26 14:10 UTC, hariclerry commented
Hello @rowasc, thanks for the feedback and references. I have worked on the feedback and I have also created another Pull request on platform-pattern-library in response to the css change. https://github.com/ushahidi/platform-pattern-library/pull/254. Thanks.

2020-10-29 11:42 UTC, Angamanga commented
@hariclerry @rowasc  Sorry I am late on this one. We can use the same methodology for rtl as we use in other places in the platform-client, so this only needs changes in the pattern-library, see my comments in the pull-request there: https://github.com/ushahidi/platform-pattern-library/pull/254/files

2020-11-18 09:08 UTC, Angamanga commented
Closing this in favour of https://github.com/ushahidi/platform-pattern-library/pull/254/files

2020-11-18 09:08 UTC, closed without merging