1555 form field type
ushahidi/platform-client pull request #1630
Opened 2020-11-27 15:39 UTC by Angamanga

This pull request makes the following changes:
- 'Edit field' in surveys now shows the type of the field 
![d9f145bc5bc2a1a1d55b8e8ecc32aee6](https://user-images.githubusercontent.com/45670033/95666174-1b1adf80-0b4f-11eb-8f7d-42a3dc618923.png)

Testing checklist:
- [ ] log into your deployment
- [ ] go to survey
- [ ] select a field to edit
- [ ] modal's title should be in format '**Edit** *field type* **field**'
- [ ] Repeat above for adding a new field. The modal's title should be in format '**Add** *field type* **field**'
- [x] I certify that I ran my checklist

[Fixes # 1555 in ushahidi/platform](https://github.com/ushahidi/platform/issues/1555)

Ping @ushahidi/platform

2020-11-27 15:41 UTC, Angamanga commented
This issue was mostly fixed by @ypresion in https://github.com/ushahidi/platform-client/pull/1559. This is a continuation with the last small fix.

2020-11-30 13:01 UTC, rowasc commented on app/settings/surveys/survey-editor.directive.js
> +        return fieldTypes[attribute.input][attribute.type];
I'd probably suggest checking fieldTypes[attribute.input] exists just in case to avoid an error throwing.

2020-11-30 13:01 UTC, rowasc requested changes
Tiny comment but the rest looks good. THanks!

2020-12-02 20:56 UTC, rowasc commented
Merged (with the comment applied) into v5-main

2020-12-03 14:30 UTC, closed without merging