Adds navigation in dropdown menus in surveys and posts
ushahidi/platform-client pull request #1653
Opened 2021-02-15 07:41 UTC by renujain31

This pull request makes the following changes:
- It makes the dropdown menu  of posts and surveys accessible via keyboard

Testing checklist:
- [ ] Login your account
- [ ] Go to the survey page
- [ ] The dropdown menu represented by three dots on the page is accessible.

- [ ] Now go to Data section.
- [ ] The dropdown menu represented by three dots alongside posts is also accessible.

- [x] I certify that I ran my checklist

Recordings:
![rec1](https://user-images.githubusercontent.com/70752431/107916363-38900800-6f8c-11eb-8b7f-6b76c3cede85.gif)
![rec2](https://user-images.githubusercontent.com/70752431/107916365-39c13500-6f8c-11eb-9221-0c0a72b5d6be.gif)

Fixes ushahidi/platform# .

Linked platform pattern library pull request: #
Ping @ushahidi/platform

2021-02-25 08:04 UTC, Angamanga requested changes
This works fine, just remove the new class on the share-button and this is good to go to QA :)

2021-02-25 08:04 UTC, Angamanga commented on app/main/posts/views/share/post-share.html
> +<button ng-class="{ 'button' : isButton(), 'button-flat': isAdd()}" class="button-survey" ng-click="openShareMenu()">
I think this is the reason for the share-button has changed appearance?

2021-03-01 10:25 UTC, Angamanga submitted a review, later dismissed
Works fine now! Thank you 🎉

2021-03-01 10:25 UTC, Angamanga commented
@Obadha2 Ready for QA 🎉

2021-04-02 10:56 UTC, Angamanga commented
@Angamanga Resolve conflicts!

2021-06-05 17:53 UTC, tuxpiper approved these changes
Stamping approval

2021-06-07 07:41 UTC, Angamanga commented
@Obadha2 Ready for QA 🎉

2021-06-07 09:02 UTC, merged

2021-06-07 15:10 UTC, Obadha2 commented
@Angamanga this doesn't quite pass.
1. The flow while tabbing down the Survey, seems to go back and forth. Could this be streamlined? (See attached GIF) 
![chrome-capture](https://user-images.githubusercontent.com/38259840/121041421-67402180-c7bb-11eb-9b4a-a9338b87f434.gif)

2. Options presented in some instances the Delete Survey option appears different from the Duplicate option. (See attached GIF) 
3.  The Delete Survey option is skipped when tabbing.