Fix: USSD cont'd (Enabled sources)
ushahidi/platform-client pull request #1825
Opened 2022-08-31 14:52 UTC by Ifycode

This pull request makes the following changes:
- To be merged into #1808 

Testing checklist:
- [x] Sources come from config file, and default is set to 'web', 'sms', 'twitter', 'email'. 
- [ ] Show or hide ussd and whatsapp sources checkboxes in post toolbar dropdown depending on if they are part of ENABLED_SOURCES
- [ ] I certify that I ran my checklist

Ping @ushahidi/platform

2022-08-31 15:45 UTC, Ifycode commented
@tuxpiper please help take a look.

2022-09-02 07:18 UTC, tuxpiper requested changes

2022-09-02 10:34 UTC, Ifycode commented on app/config.js.j2
> +  enabledSources: '{{ ENABLED_SOURCES }}'
> If the environment variable is not present, jinja2 will not add the entry to window.ushahidi, and app.js should use a default instead.

This is the part I needed to hear @tuxpiper Thank you so much

2022-09-02 10:38 UTC, Ifycode commented on legacy/app/app.js
> +        ENABLED_SOURCES: window.ushahidi.sources.filter(source => source !== 'ussd' && source !== 'whatsapp')
So by this you mean this line should have been this ?

````
ENABLED_SOURCES: window.ushahidi.sources || ['sms', 'twitter', 'web', 'email']

````

2022-09-02 10:58 UTC, Ifycode commented on root/src/config.js
> +    sources: ['sms', 'twitter', 'web', 'email', 'whatsapp', 'ussd']
So from the other review comments, I think I see my mistake. It's that I never understood the purpose... 

The user should be the one to set it here config.js, that is if they want a change. So `window.ushahidi` object should stay empty in config.js.
But if the user doesn't add their own sources property in here, the default in the app.js would take effect: https://github.com/ushahidi/platform-client/pull/1825#discussion_r961541455

And then I could probably add to the commented out code in config.js to help the user know they can define the sources they want if they don't want default to take effect:
````
// sources: ['sms', 'twitter', 'web', 'email', 'whatsapp', 'ussd']
````

2022-09-02 11:27 UTC, Ifycode commented
@tuxpiper I have made the new changes. Please help review. And also if I should merge into the main USSD PR.

2022-09-02 11:54 UTC, Ifycode commented
@tuxpiper I have made the new changes and fixed failing tests. Please help review. And also if I should merge into the main USSD PR.

2022-09-05 07:14 UTC, tuxpiper approved these changes
Great job @Ifycode  🙏  It's ready to merge!

2022-09-05 07:38 UTC, merged